### ISSUE TITLE
Method to use custom activity transition

### ISSUE THREAD

**Issue by callingmedic911** [braintree/browser-switch-android#15]
### General information

* SDK/Library version: 0.2.0

### Feature Request
Request to add method
```
public void browserSwitch(int requestCode, Intent intent, Bundle options) { ... }
```
(Bundle argument), so that we can customize activity start animation.
I'll be happy make PR, please let me know.

**Comment by quinnjn** [comment]
That sounds awesome, a PR would be amazing!

**Comment by callingmedic911** [comment]
I've made a pr: https://github.com/braintree/browser-switch-android/pull/16 
I also suggest to add steps to customize Chrome Custom Tabs.
For anyone looking here's example how you can customize:
```java
import static androidx.browser.customtabs.CustomTabsIntent.EXTRA_TOOLBAR_COLOR;

Intent browserIntent =
                        new Intent(Intent.ACTION_VIEW, intentContainingUri)
                        .addFlags(FLAG_ACTIVITY_NEW_TASK)
                        .putExtra(EXTRA_TOOLBAR_COLOR, getResources().getColor(R.color.colorPrimary));
browserSwitch(AUTHORIZE_PAYMENT, browserIntent);
```

Basically you can customization almost everything since it is a Intent based communication. So just look here: https://github.com/GoogleChrome/custom-tabs-client/blob/master/customtabs/src/android/support/customtabs/CustomTabsIntent.java and see what you need.
