### ISSUE TITLE
Enquiry: Url tracking on Chrome Custom tabs

### ISSUE THREAD

**Issue by biodunalfet** [braintree/browser-switch-android#8]
Hi 
Is it possible to track which url is currently being loaded on the chrome tabs using this library?

**Comment by quinnjn** [comment]
Not currently. This library relies on Intents to communicate data so if we add the feature you would get that data after the user has finished the flow which for most use cases I can think of isn't useful.

Can you explain the use case for URL tracking?

**Comment by biodunalfet** [comment]
Hi @quinnjn I work at a payments company and we have an drop-in-UI type android sdk for collecting payments. For some of our payment models, the users fill a form and are then taken to a url to complete the payment. We load that url in a webview and listen for certain strings in the url being loaded in the webview to determine if the payment is complete or not. I've been thinking of moving this to Chrome Custom Tabs for a while till I stumbled on this library. Can your library help out here?

**Comment by quinnjn** [comment]
I think this library might be able to help you. I don't know the details enough to state for sure though.

This library is highly coupled to the fact that you are interacting with a service that asks for a redirect/callback URL, think of a basic OAuth flow. If the page you're interacting with has that, this is the library for you!

If the payment method does not allow for a redirect URL your current solution might be the solution you have to stick with.
